ACS-514: Check compatibility with Glacier version 2.1.0-RC1, S3 Connector version 3.1.0-RC3
Alfresco/acs-packaging pull request #1612
Opened 2020-08-25 12:34 UTC by rgherghelas

…ctor version 3.1.0-RC3

2020-08-25 12:52 UTC, aforascu approved these changes

2020-08-25 15:07 UTC, ancutam requested changes

2020-08-25 15:07 UTC, ancutam commented on tests/tas-all-amps/src/test/java/org/alfresco/rest/discovery/DiscoveryTests.java
> +                "alfresco-glacier-connector-repo"
Missing comma after ` "alfresco-rm-enterprise-repo"`, in the amps list.

2020-08-26 07:17 UTC, ancutam approved these changes

2020-08-26 16:08 UTC, ancutam commented
Glacier Connector E2E tests passed https://travis-ci.com/github/Alfresco/glacier-connector/builds/181468581 
So this PR can be merged to master.

2020-08-26 16:20 UTC, merged