ACS-8460: Bump hxi-connector to 1.0.0-A8
Alfresco/acs-packaging pull request #2894
Opened 2024-08-08 16:28 UTC by krdabrowski

2024-08-09 07:43 UTC, dsibilio approved these changes

2024-08-09 08:20 UTC, mpichura approved these changes

2024-08-09 08:35 UTC, mpichura requested changes
I don't think all tests have been executed in the checks.

2024-08-09 08:45 UTC, damianujma approved these changes

2024-08-09 13:37 UTC, krdabrowski commented
@mpichura on branch `release/7.3.N` those tests are missing in CI - they where added within Release 7.4. I think we can assume, that if build on 7.4 will pass, then this also should be safe

2024-08-29 14:08 UTC, mpichura approved these changes

2024-08-30 05:57 UTC, merged